### ISSUE TITLE
`freeze()` helper function doesn't work with `Object.create(null)`

### ISSUE THREAD

**Issue by pahbloo** [cferdinandi/vanilla-js-toolkit#14]
Example:
https://codepen.io/pahbloo/pen/NWbYrVJ

Cause and possible solution:
https://eslint.org/docs/rules/no-prototype-builtins

btw, Chris, I'm a big fan of your work. You show how it's possible to make great things in a simple way! 😋👍

**Comment by cferdinandi** [comment]
Good catch. Thanks for the fix!
