### ISSUE TITLE
ReplaceAll gives incorrect result

### ISSUE THREAD

**Issue by khokm** [cferdinandi/vanilla-js-toolkit#17]
Test: `"s.t.a.l.k.e.r".replaceAll(".", "")`
Expected: "stalker"
Actual result: ""
This is the result of lack of string escaping before creating regexp.
I already made an alternative implementation of replaceAll (using 'String.replace' in loop).
If this issue is actual, i can make a PR.

**Comment by cferdinandi** [comment]
Oh yea, open to a fix.
