### ISSUE TITLE
constructor pattern documentation typo

### ISSUE THREAD

**Issue by davidmcguiredesign** [cferdinandi/vanilla-js-toolkit#22]
Spotted a typo in the example for the [constructor documentation (line 23)](https://github.com/cferdinandi/vanilla-js-toolkit/blob/3e5557e95ca9b2a51a4685753b921f9abd27d59a/content/boilerplates/constructor.md?plain=1#L23): to call the object created, `dug.total` would need a second 'g'. 

I’m a regular reader of your newsletter. Thanks for your continuing investment in new JS developers!

**Comment by cferdinandi** [comment]
Good catch! Just pushed a fix that should be live shortly.
