### ISSUE TITLE
Accordion doesn't work, there are no headings

### ISSUE THREAD

**Issue by Danny-Engelman** [cferdinandi/vanilla-js-toolkit#23]
I copied pasted your code to JSFiddle, but there are no headings found:

https://jsfiddle.net/WebComponents/c29bk3sw/

**Comment by cferdinandi** [comment]
Maybe some weird quirk with JSFiddle? I just copy/pasted your code directly into CodePen and it works as expected: https://codepen.io/cferdinandi/pen/KKEXJZL

**Comment by Danny-Engelman** [comment]
It is not a copy. The ``<script>`` needs to be before the HTML is parsed

**Comment by cferdinandi** [comment]
Why does it "need" to be? 

The reason that's causing errors in this case is because the script, already on the page, immediately instantiates the `accordion-group` element, whose child elements have not yet been added to the DOM yet.

**Comment by cferdinandi** [comment]
@Danny-Engelman Oh also, if you for some reason truly _need_ to load the script in the header, you'll want to wrap it in a `DOMContentLoaded` event listener, so that it doesn't run until all of the DOM nodes have been loaded.

Here's an updated demo: https://codepen.io/cferdinandi/pen/OJqxqdV
