### ISSUE TITLE
placeholders.js incorrectly handling if matched property value is 0 or false

### ISSUE THREAD

**Issue by bertwagner** [cferdinandi/vanilla-js-toolkit#3]
On the line:
`if (!data[match]) return '{{' + match + '}}';`

a bug occurs if the matched property value equals 0 or false:
eg. `var data = { firstProperty = 0, secondProperty = false };`

One possible solution is to check if `data` has a property instead of rendering the actual value:
`if (!data.hasOwnProperty(match)) return '{{' + match + '}}';`

Not sure if that's the best way to do it though so I didn't want to open a pull request.

Thanks for sharing this library.

**Comment by cferdinandi** [comment]
Good catch!

I think your approach is probably the right way to handle this.

**Comment by cferdinandi** [comment]
Fixed. Thanks!
