### ISSUE TITLE
Selectors - missing getElementById()

### ISSUE THREAD

**Issue by orionrush** [cferdinandi/vanilla-js-toolkit#7]
I'm just wondering if the Selectors section should include `document.getElementById()`?

[https://github.com/cferdinandi/vanilla-js-toolkit/tree/master/content/reference/selectors](https://github.com/cferdinandi/vanilla-js-toolkit/tree/master/content/reference/selectors)

**Comment by cferdinandi** [comment]
This is supposed to be a reference for common methods rather than comprehensive documentation. Frankly, `getElementById()` doesn’t have enough utility when `querySelector()` exists.
